"""anotade

Revision ID: 1253b811b13f
Revises: 5fd5ebeadeab
Create Date: 2023-10-02 17:01:12.945269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1253b811b13f'
down_revision: Union[str, None] = '5fd5ebeadeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='role'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'roles',
               existing_type=postgresql.ENUM('admin', 'moderator', 'user', name='role'),
               nullable=True)
    # ### end Alembic commands ###
