"""Init_2

Revision ID: 9c548bf65716
Revises: cc057a8a4dbb
Create Date: 2023-10-11 19:26:34.869498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c548bf65716'
down_revision: Union[str, None] = 'cc057a8a4dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('addressbook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addressbook',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('addressbook_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=55), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=55), autoincrement=False, nullable=False),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='addressbook_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='addressbook_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('contact_type', postgresql.ENUM('email', 'phone', name='contacttype'), autoincrement=False, nullable=False),
    sa.Column('contact_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['addressbook.id'], name='contacts_contact_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey')
    )
    # ### end Alembic commands ###
